USE DATABASE "MY_DATABASE_DEMO";

CREATE SCHEMA "MY_SCHEMA_DEMO";

CREATE ROLE "MY_ROLE_DEMO";
CREATE USER "MY_USER_DEMO"
    PASSWORD = "YourStrongPassword123!"
    DEFAULT_ROLE = "MY_ROLE_DEMO"
    DEFAULT_WAREHOUSE = "MY_WAREHOUSE_DEMO"
    DEFAULT_NAMESPACE = "MY_DATABASE_DEMO.MY_SCHEMA_DEMO";
